Update test for build container

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -35,11 +35,11 @@ jobs:
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Extract metadata (tags, labels) for Docker
-        id: meta
-        uses: docker/metadata-action@v5
-        with:
-          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
+      #- name: Extract metadata (tags, labels) for Docker
+      #  id: meta
+      #  uses: docker/metadata-action@v5
+      #  with:
+      #    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
 
       - name: Build a image
         id: push
@@ -47,21 +47,31 @@ jobs:
         with:
           context: .
           push: false
-          tags: ${{ steps.meta.outputs.tags }}
+          #tags: ${{ steps.meta.outputs.tags }}
+          tags: ex1:test
           #platforms: linux/amd64,linux/arm64
-          labels: ${{ steps.meta.outputs.labels }}
+          #labels: ${{ steps.meta.outputs.labels }}
+          labels: test
 
       - name: Start a container from the image
         run: |
           docker images
-          docker run -d --name test -p 9100:9100 ${{ steps.meta.outputs.tags }}
-          docker ps
+          # docker run -d --name test -p 9100:9100 ${{ steps.meta.outputs.tags }}
+          docker compose up -d
+          docker compose ps
 
       - name: Test the container
         run: |
-          sleep 5
-          docker ps
+          sleep 10
+          docker compose ps -a
           curl --silent --retry 3 --include  http://127.0.0.1:9100/ping | grep "200 OK" 
           [ $? -ne 0 ] && (echo "error"; exit 1)
+          curl --silent --retry 3 --include  http://127.0.0.1:9100/info | grep "200 OK" 
+          [ $? -ne 0 ] && (echo "error"; exit 1)
+          curl --silent --retry 3 --include  http://127.0.0.1:9100/healthz | grep "500 INTERNAL SERVER ERROR" 
+          [ $? -ne 0 ] && (echo "error"; exit 1)
+          curl --silent --retry 3 --include  http://127.0.0.1:9100/readiness | grep "200 OK" 
+          [ $? -ne 0 ] && (echo "error"; exit 1)
+
           exit 0
 
